/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import DecorationImage from 'src/images/ReasonCard_Decoration.png';
import { styled } from '@mui/material/styles';
import { ReasonCardProps } from 'src/types';

const ReasonCard1: any = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  border: `1px solid rgba(0, 0, 0, 0.1)`,
  boxSizing: `border-box`,
  borderRadius: `10px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  height: `210px`,
  width: '100%',
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `20px 16px`,
  overflow: `hidden`,
});

const Decoration: any = styled('img')({
  height: `45px`,
  width: `45px`,
  margin: `0px`,
});

const Title: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `600`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `32px`,
  textTransform: `none`,
  margin: `8px 0px 0px 0px`,
});

const Subtitle: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `21px`,
  textTransform: `none`,
  alignSelf: `stretch`,
  margin: `8px 0px 0px 0px`,
});

function ReasonCard(props: ReasonCardProps): JSX.Element {
  return (
    <ReasonCard1 className={props.className}>
      <Decoration src={DecorationImage} loading="lazy" alt={'Decoration'} />
      <Title>{`Guaranteed Allocation`}</Title>
      <Subtitle>
        {`Within the specified time you will receive invite to a claim page `}
      </Subtitle>
    </ReasonCard1>
  );
}

export default ReasonCard;
