/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';
import ReasonCard from 'src/components/ReasonCard/ReasonCard';
import Button1 from 'src/components/Button1/Button1';
import { BuyReasonsProps } from 'src/types';

const BuyReasons1: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `119px 64px 106px 64px`,
  boxSizing: `border-box`,
  height: 'auto',
  width: 'fit-content',
});

const TopBlock: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const Frame39907: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const WhyYouShouldBuyNft: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `700`,
  fontSize: `40px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `60px`,
  textTransform: `none`,
  margin: `0px`,
});

const NftGivesYouAGuaranteSpan1: any = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `32px`,
  textTransform: `none`,
});

const NftGivesYouAGuaranteSpan2: any = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `600`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `32px`,
  textTransform: `none`,
});

const NftGivesYouAGuaranteSpan3: any = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `32px`,
  textTransform: `none`,
});

const NftGivesYouAGuaranteSpan4: any = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `600`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `32px`,
  textTransform: `none`,
});

const NftGivesYouAGuaranteSpan5: any = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `32px`,
  textTransform: `none`,
});

const NftGivesYouAGuarante: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: 'unset',
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `32px`,
  textTransform: `none`,
  width: `544px`,
  margin: `10px 0px 0px 0px`,
});

const Frame39906: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px 0px 0px 128px`,
});

const Group11: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `380px`,
  height: `119px`,
  margin: `0px`,
});

const Group9: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `380px`,
  height: `119px`,
  left: `0px`,
  top: `0px`,
});

const Rectangle30: any = styled('div')({
  backgroundColor: `rgba(14, 28, 247, 1)`,
  borderRadius: `10px`,
  width: `89px`,
  height: `119px`,
  position: `absolute`,
  left: `194px`,
  top: `0px`,
});

const Rectangle31: any = styled('div')({
  backgroundColor: `rgba(14, 28, 247, 1)`,
  borderRadius: `10px`,
  width: `89px`,
  height: `119px`,
  position: `absolute`,
  left: `291px`,
  top: `0px`,
});

const Rectangle32: any = styled('div')({
  backgroundColor: `rgba(14, 28, 247, 1)`,
  borderRadius: `10px`,
  width: `89px`,
  height: `119px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Rectangle33: any = styled('div')({
  backgroundColor: `rgba(14, 28, 247, 1)`,
  borderRadius: `10px`,
  width: `89px`,
  height: `119px`,
  position: `absolute`,
  left: `97px`,
  top: `0px`,
});

const Q0: any = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `700`,
  fontSize: `86px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `60px`,
  textTransform: `none`,
  position: `absolute`,
  left: `16px`,
  top: `30px`,
});

const Q01: any = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `700`,
  fontSize: `86px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `60px`,
  textTransform: `none`,
  position: `absolute`,
  left: `113px`,
  top: `30px`,
});

const Q02: any = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `700`,
  fontSize: `86px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `60px`,
  textTransform: `none`,
  position: `absolute`,
  left: `210px`,
  top: `30px`,
});

const Q8: any = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `700`,
  fontSize: `86px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `60px`,
  textTransform: `none`,
  position: `absolute`,
  left: `307px`,
  top: `30px`,
});

const Frame39905: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px 0px 0px 26px`,
});

const NftMint: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(14, 28, 247, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `600`,
  fontSize: `32px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `60px`,
  textTransform: `none`,
  margin: `0px`,
});

const PoremIpsumDolorSitAm: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `500`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `21px`,
  textTransform: `none`,
  opacity: `0.5`,
  width: `232px`,
  margin: `0px`,
});

const Cards: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin: `38px 0px 0px 0px`,
});

const ReasonCard1: any = styled(ReasonCard)(({ theme }: any) => ({
  flex: `1`,
  height: `210px`,
  margin: `0px`,
}));

const ReasonCard2: any = styled(ReasonCard)(({ theme }: any) => ({
  flex: `1`,
  height: `210px`,
  margin: `0px 0px 0px 32px`,
}));

const ReasonCard3: any = styled(ReasonCard)(({ theme }: any) => ({
  flex: `1`,
  height: `210px`,
  margin: `0px 0px 0px 32px`,
}));

const ReasonCard4: any = styled(ReasonCard)(({ theme }: any) => ({
  flex: `1`,
  height: `210px`,
  margin: `0px 0px 0px 32px`,
}));

const ActionButtons: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `38px 0px 0px 0px`,
});

const Button2: any = styled(Button1)(({ theme }: any) => ({
  margin: `0px`,
}));

const Button3: any = styled(Button1)(({ theme }: any) => ({
  margin: `0px 0px 0px 17px`,
}));

function BuyReasons(props: BuyReasonsProps): JSX.Element {
  return (
    <BuyReasons1 className={props.className}>
      <TopBlock>
        <Frame39907>
          <WhyYouShouldBuyNft>{`Why you should buy NFT?`}</WhyYouShouldBuyNft>
          <NftGivesYouAGuarante>
            <NftGivesYouAGuaranteSpan1>{`NFT gives you a guaranteed chance to buy your allocation. We have only `}</NftGivesYouAGuaranteSpan1>
            <NftGivesYouAGuaranteSpan2>{`1 000 NFTs`}</NftGivesYouAGuaranteSpan2>
            <NftGivesYouAGuaranteSpan3>{` with a total amount of allocation worth of `}</NftGivesYouAGuaranteSpan3>
            <NftGivesYouAGuaranteSpan4>{`$1М`}</NftGivesYouAGuaranteSpan4>
            <NftGivesYouAGuaranteSpan5>{`.`}</NftGivesYouAGuaranteSpan5>
          </NftGivesYouAGuarante>
        </Frame39907>
        <Frame39906>
          <Group11>
            <Group9>
              <Rectangle30></Rectangle30>
              <Rectangle31></Rectangle31>
              <Rectangle32></Rectangle32>
              <Rectangle33></Rectangle33>
            </Group9>
            <Q0>{`0`}</Q0>
            <Q01>{`0`}</Q01>
            <Q02>{`0`}</Q02>
            <Q8>{`8`}</Q8>
          </Group11>
          <Frame39905>
            <NftMint>{`NFT MINT`}</NftMint>
            <PoremIpsumDolorSitAm>
              {`Porem ipsum dolor sit amet, consectetur adipiscing elit.`}
            </PoremIpsumDolorSitAm>
          </Frame39905>
        </Frame39906>
      </TopBlock>
      <Cards>
        <ReasonCard1 />
        <ReasonCard2 />
        <ReasonCard3 />
        <ReasonCard4 />
      </Cards>
      <ActionButtons>
        <Button2 />
        <Button3 />
      </ActionButtons>
    </BuyReasons1>
  );
}

export default BuyReasons;
