/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';
import InvestorCard from 'src/components/InvestorCard/InvestorCard';
import { InvestorsViewProps } from 'src/types';

const InvestorsView1: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `60px 64px`,
  boxSizing: `border-box`,
  height: 'auto',
  width: 'fit-content',
});

const InvestorsAndPartners: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `700`,
  fontSize: `40px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `60px`,
  textTransform: `none`,
  margin: `0px`,
});

const Frame39901: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `44px 0px 0px 0px`,
});

const Line1: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const InvestorCard1: any = styled(InvestorCard)(({ theme }: any) => ({
  width: `304px`,
  height: `96px`,
  margin: `0px`,
}));

const InvestorCard2: any = styled(InvestorCard)(({ theme }: any) => ({
  width: `304px`,
  height: `96px`,
  margin: `0px 0px 0px 32px`,
}));

const InvestorCard3: any = styled(InvestorCard)(({ theme }: any) => ({
  width: `304px`,
  height: `96px`,
  margin: `0px 0px 0px 32px`,
}));

const InvestorCard4: any = styled(InvestorCard)(({ theme }: any) => ({
  width: `304px`,
  height: `96px`,
  margin: `0px 0px 0px 32px`,
}));

const Line2: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `20px 0px 0px 0px`,
});

const InvestorCard5: any = styled(InvestorCard)(({ theme }: any) => ({
  width: `304px`,
  height: `96px`,
  margin: `0px`,
}));

const InvestorCard6: any = styled(InvestorCard)(({ theme }: any) => ({
  width: `304px`,
  height: `96px`,
  margin: `0px 0px 0px 32px`,
}));

const InvestorCard7: any = styled(InvestorCard)(({ theme }: any) => ({
  width: `304px`,
  height: `96px`,
  margin: `0px 0px 0px 32px`,
}));

const InvestorCard8: any = styled(InvestorCard)(({ theme }: any) => ({
  width: `304px`,
  height: `96px`,
  margin: `0px 0px 0px 32px`,
}));

const InvestorCard9: any = styled(InvestorCard)(({ theme }: any) => ({
  height: `96px`,
  width: `304px`,
  margin: `20px 0px 0px 0px`,
}));

function InvestorsView(props: InvestorsViewProps): JSX.Element {
  return (
    <InvestorsView1 className={props.className}>
      <InvestorsAndPartners>{`Investors and partners`}</InvestorsAndPartners>
      <Frame39901>
        <Line1>
          <InvestorCard1 />
          <InvestorCard2 />
          <InvestorCard3 />
          <InvestorCard4 />
        </Line1>
        <Line2>
          <InvestorCard5 />
          <InvestorCard6 />
          <InvestorCard7 />
          <InvestorCard8 />
        </Line2>
        <InvestorCard9 />
      </Frame39901>
    </InvestorsView1>
  );
}

export default InvestorsView;
