/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';
import TopView from 'src/components/TopView/TopView';
import AboutView from 'src/components/AboutView/AboutView';
import UniqueView from 'src/components/UniqueView/UniqueView';
import CompetitorComparisonView from 'src/components/CompetitorComparisonView/CompetitorComparisonView';
import InvestorsView from 'src/components/InvestorsView/InvestorsView';
import BuyReasons from 'src/components/BuyReasons/BuyReasons';
import HowItWorksView from 'src/components/HowItWorksView/HowItWorksView';
import LaunchpadAndExchangesView from 'src/components/LaunchpadAndExchangesView/LaunchpadAndExchangesView';
import BuyView from 'src/components/BuyView/BuyView';
import EmailView from 'src/components/EmailView/EmailView';
import { IvendpayNftProps } from 'src/types';

const IvendpayNft1: any = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
  height: 'auto',
  width: 'fit-content',
});

const TopView1: any = styled(TopView)(({ theme }: any) => ({
  height: `648px`,
  width: `1440px`,
  margin: `0px`,
}));

const AboutView1: any = styled(AboutView)(({ theme }: any) => ({
  margin: `0px`,
}));

const UniqueView1: any = styled(UniqueView)(({ theme }: any) => ({
  margin: `0px`,
}));

const CompetitorComparison: any = styled(CompetitorComparisonView)(
  ({ theme }: any) => ({
    margin: `0px`,
  })
);

const InvestorsView1: any = styled(InvestorsView)(({ theme }: any) => ({
  margin: `0px`,
}));

const BuyReasons1: any = styled(BuyReasons)(({ theme }: any) => ({
  margin: `0px`,
}));

const HowItWorksView1: any = styled(HowItWorksView)(({ theme }: any) => ({
  margin: `0px`,
}));

const LaunchpadAndExchange: any = styled(LaunchpadAndExchangesView)(
  ({ theme }: any) => ({
    margin: `0px`,
  })
);

const BuyView1: any = styled(BuyView)(({ theme }: any) => ({
  margin: `0px`,
}));

const EmailView1: any = styled(EmailView)(({ theme }: any) => ({
  width: `1441px`,
  margin: `0px`,
}));

function IvendpayNft(props: IvendpayNftProps): JSX.Element {
  return (
    <IvendpayNft1 className={props.className}>
      <TopView1 />
      <AboutView1 />
      <UniqueView1 />
      <CompetitorComparison />
      <InvestorsView1 />
      <BuyReasons1 />
      <HowItWorksView1 />
      <LaunchpadAndExchange />
      <BuyView1 />
      <EmailView1 />
    </IvendpayNft1>
  );
}

export default IvendpayNft;
