/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import Image5Image from 'src/images/CardImage_image_5.png';
import { styled } from '@mui/material/styles';
import { CardImageProps } from 'src/types';

const Property1App: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `72px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
});

const Image5: any = styled('img')({
  height: `72px`,
  width: `173px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `-91px`,
  top: `0px`,
});

function CardImage(props: CardImageProps): JSX.Element {
  return (
    <Property1App className={props.className}>
      <Image5 src={Image5Image} loading="lazy" alt={'image 5'} />
    </Property1App>
  );
}

export default CardImage;
