/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';
import BuyOption from 'src/components/BuyOption/BuyOption';
import { BuyViewProps } from 'src/types';

const BuyView1: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `8px 64px 81px 64px`,
  boxSizing: `border-box`,
  height: 'auto',
  width: 'fit-content',
});

const ChooseYourGuaranteed: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `700`,
  fontSize: `40px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `60px`,
  textTransform: `none`,
  margin: `0px`,
});

const BuyOptions: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `50px 0px 0px 0px`,
});

const BuyOption1: any = styled(BuyOption)(({ theme }: any) => ({
  width: `416px`,
  height: `328px`,
  margin: `0px`,
}));

const BuyOption2: any = styled(BuyOption)(({ theme }: any) => ({
  width: `416px`,
  height: `328px`,
  margin: `0px 0px 0px 35px`,
}));

const BuyOption3: any = styled(BuyOption)(({ theme }: any) => ({
  width: `416px`,
  height: `328px`,
  margin: `0px 0px 0px 35px`,
}));

function BuyView(props: BuyViewProps): JSX.Element {
  return (
    <BuyView1 className={props.className}>
      <ChooseYourGuaranteed>
        {`Choose your guaranteed allocation`}
      </ChooseYourGuaranteed>
      <BuyOptions>
        <BuyOption1 />
        <BuyOption2 />
        <BuyOption3 />
      </BuyOptions>
    </BuyView1>
  );
}

export default BuyView;
