/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';
import { LaunchpadAndExchangesViewProps } from 'src/types';

const LaunchpadAndExchange: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-end`,
  padding: `158px 64px`,
  boxSizing: `border-box`,
  height: 'auto',
  width: 'fit-content',
});

const Texts: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const LaunchpadsAndExchang: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `700`,
  fontSize: `40px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `60px`,
  textTransform: `none`,
  margin: `0px`,
});

const Subtitles: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `18px 0px 0px 0px`,
});

const LaunchpadsMarketMakiSpan1: any = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `32px`,
  textTransform: `none`,
});

const LaunchpadsMarketMakiSpan2: any = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `600`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `32px`,
  textTransform: `none`,
});

const LaunchpadsMarketMakiSpan3: any = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `32px`,
  textTransform: `none`,
});

const LaunchpadsMarketMaki: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: 'unset',
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `32px`,
  textTransform: `none`,
  width: `305px`,
  margin: `0px`,
});

const CeXsForTheListingOkxSpan1: any = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `32px`,
  textTransform: `none`,
});

const CeXsForTheListingOkxSpan2: any = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `600`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `32px`,
  textTransform: `none`,
});

const CeXsForTheListingOkxSpan3: any = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `32px`,
  textTransform: `none`,
});

const CeXsForTheListingOkx: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: 'unset',
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `32px`,
  textTransform: `none`,
  width: `304px`,
  margin: `0px 0px 0px 32px`,
});

const Dates: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px 0px 0px 32px`,
});

const Q32023: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(14, 28, 247, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `600`,
  fontSize: `64px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `32px`,
  textTransform: `none`,
  margin: `0px`,
});

const Decoration: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  height: `72px`,
  width: `640px`,
  margin: `30px 0px 0px 0px`,
});

const Rectangle42: any = styled('div')({
  backgroundColor: `rgba(14, 28, 247, 1)`,
  borderRadius: `0px 0px 10px 10px`,
  width: `640px`,
  height: `24px`,
  position: `absolute`,
  left: `0px`,
  top: `48px`,
});

const Rectangle43: any = styled('div')({
  opacity: `0.10000000149011612`,
  backgroundColor: `rgba(14, 28, 247, 1)`,
  borderRadius: `10px 10px 0px 0px`,
  width: `640px`,
  height: `24px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Rectangle44: any = styled('div')({
  opacity: `0.5`,
  backgroundColor: `rgba(14, 28, 247, 1)`,
  width: `640px`,
  height: `24px`,
  position: `absolute`,
  left: `0px`,
  top: `24px`,
});

function LaunchpadAndExchangesView(
  props: LaunchpadAndExchangesViewProps
): JSX.Element {
  return (
    <LaunchpadAndExchange className={props.className}>
      <Texts>
        <LaunchpadsAndExchang>
          {`Launchpads and exchanges`}
        </LaunchpadsAndExchang>
        <Subtitles>
          <LaunchpadsMarketMaki>
            <LaunchpadsMarketMakiSpan1>{`Launchpads:`}</LaunchpadsMarketMakiSpan1>
            <LaunchpadsMarketMakiSpan2>{` MarketMaking Pro Launchpad, Tenset, Poolz Finance`}</LaunchpadsMarketMakiSpan2>
            <LaunchpadsMarketMakiSpan3>{` — Estimate Listing Date: Q3, 2023 `}</LaunchpadsMarketMakiSpan3>
          </LaunchpadsMarketMaki>
          <CeXsForTheListingOkx>
            <CeXsForTheListingOkxSpan1>{`CEXs for the listing: `}</CeXsForTheListingOkxSpan1>
            <CeXsForTheListingOkxSpan2>{`OKX, Gate.io, XT.com, Azbit`}</CeXsForTheListingOkxSpan2>
            <CeXsForTheListingOkxSpan3>{` — Estimate Listing Date: Q3, 2023`}</CeXsForTheListingOkxSpan3>
          </CeXsForTheListingOkx>
        </Subtitles>
      </Texts>
      <Dates>
        <Q32023>{`Q3, 2023 `}</Q32023>
        <Decoration>
          <Rectangle42></Rectangle42>
          <Rectangle43></Rectangle43>
          <Rectangle44></Rectangle44>
        </Decoration>
      </Dates>
    </LaunchpadAndExchange>
  );
}

export default LaunchpadAndExchangesView;
