/**********************************************************************
 *
 *   Types file generated by Quest
 *
 *   Types for the components props go in this file
 *   To set up custom types for the components props, edit the corresponding types in this file
 *   Once you edit a type to no longer by "any", be careful to not override it on your next export
 *   Verify diff before merging
 *
 *   For help and further details refer to:
 *   https://docs.quest.ai/react/fundamentals/exporting-code
 *
 *
 **********************************************************************/

export interface SampleCardProps {
  className?: any;
  metadata: any;
}

export interface SampleCardGridProps {
  className?: any;
}

export interface IvendpayNftProps {
  className?: any;
}

export interface Frame7Props {
  className?: any;
}

export interface Frame13Props {
  className?: any;
}

export interface Frame39895Props {
  className?: any;
}

export interface Frame39900Props {
  className?: any;
}

export interface Frame39902Props {
  className?: any;
}

export interface Frame39909Props {
  className?: any;
}

export interface Frame39913Props {
  className?: any;
}

export interface Frame39917Props {
  className?: any;
}

export interface Frame39923Props {
  className?: any;
}

export interface Frame39921Props {
  className?: any;
}

export interface Frame39888Props {
  className?: any;
}

export interface Button1Props {
  className?: any;
}

export interface CardImageProps {
  className?: any;
}

export interface TableNameProps {
  className?: any;
}

export interface InvestorCardProps {
  className?: any;
}

export interface ReasonCardProps {
  className?: any;
}

export interface PointProps {
  className?: any;
}

export interface IvendpayNftProps {
  className?: any;
}

export interface TopViewProps {
  className?: any;
}

export interface Button1Props {
  className?: any;
}

export interface AboutViewProps {
  className?: any;
}

export interface CardImageProps {
  className?: any;
}

export interface UniqueViewProps {
  className?: any;
}

export interface CompetitorComparisonViewProps {
  className?: any;
}

export interface TableNameProps {
  className?: any;
}

export interface InvestorsViewProps {
  className?: any;
}

export interface InvestorCardProps {
  className?: any;
  Logo: any;
}

export interface BuyReasonsProps {
  className?: any;
}

export interface ReasonCardProps {
  className?: any;
}

export interface HowItWorksViewProps {
  className?: any;
}

export interface PointProps {
  className?: any;
  Text: any;
  Number: any;
}

export interface LaunchpadAndExchangesViewProps {
  className?: any;
}

export interface BuyViewProps {
  className?: any;
}

export interface BuyOptionProps {
  className?: any;
}

export interface EmailViewProps {
  className?: any;
}
