/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import LevendpayLogoImage from 'src/images/TopView_LevendpayLogo.png';
import Polygon2Image from 'src/images/TopView_Polygon_2.png';
import { styled } from '@mui/material/styles';
import Button1 from 'src/components/Button1/Button1';
import { TopViewProps } from 'src/types';

const TopView1: any = styled('div')({
  backgroundColor: `rgba(14, 28, 247, 1)`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `648px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
});

const LevendpayLogo: any = styled('img')({
  height: `29px`,
  width: `152px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `64px`,
  top: `46px`,
});

const MainContent: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  left: `280px`,
  top: `183px`,
});

const HurryUpToGrabIvendPa: any = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `700`,
  fontSize: `64px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `84px`,
  textTransform: `none`,
  width: `880px`,
  margin: `0px`,
});

const BuyNfTsThatWillGiveY: any = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `32px`,
  textTransform: `none`,
  width: `412px`,
  margin: `17px 0px 0px 0px`,
});

const Button2: any = styled(Button1)(({ theme }: any) => ({
  margin: `17px 0px 0px 0px`,
}));

const Decoration: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `1170.88px`,
  height: `733.21px`,
  left: `126px`,
  top: `-52px`,
});

const Rectangle42216: any = styled('div')({
  opacity: `0.10000000149011612`,
  border: `25px solid rgba(255, 255, 255, 1)`,
  boxSizing: `border-box`,
  borderRadius: `171px`,
  width: `213px`,
  height: `213px`,
  position: `absolute`,
  left: `0px`,
  top: `359px`,
});

const Rectangle42217: any = styled('div')({
  opacity: `0.10000000149011612`,
  border: `25px solid rgba(255, 255, 255, 1)`,
  boxSizing: `border-box`,
  borderRadius: `50px`,
  width: `176px`,
  height: `176px`,
  position: `absolute`,
  left: `762px`,
  top: `0px`,
});

const Polygon2: any = styled('img')({
  height: `250px`,
  width: `273.35px`,
  position: `absolute`,
  left: `898px`,
  top: `483px`,
});

function TopView(props: TopViewProps): JSX.Element {
  return (
    <TopView1 className={props.className}>
      <LevendpayLogo
        src={LevendpayLogoImage}
        loading="lazy"
        alt={'LevendpayLogo'}
      />
      <MainContent>
        <HurryUpToGrabIvendPa>
          {`Hurry up to grab IvendPay private sale NFTs!`}
        </HurryUpToGrabIvendPa>
        <BuyNfTsThatWillGiveY>
          {`Buy NFTs that will give you guaranteed token allocation when the private sale starts!
`}
        </BuyNfTsThatWillGiveY>
        <Button2 />
      </MainContent>
      <Decoration>
        <Rectangle42216></Rectangle42216>
        <Rectangle42217></Rectangle42217>
        <Polygon2 src={Polygon2Image} loading="lazy" alt={'Polygon 2'} />
      </Decoration>
    </TopView1>
  );
}

export default TopView;
